# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TechforceReact' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TechforceReact
  inherit! :search_paths
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'FirebaseInstanceID'
  pod 'GoogleToolboxForMac'
  pod 'Google/SignIn'
  # target 'TechforceReact-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  target 'TechforceReactTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# target 'TechforceReact-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!
#
#   # Pods for TechforceReact-tvOS
#
#   target 'TechforceReact-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end
#
# end
